### ISSUE TITLE
Todo for V1

### ISSUE THREAD

**Issue by StumbDev** [StumbDev/basktt#1]
# Todo for V1️⃣ Launch 🚀
- [x] Add conditions support, example: 
```typescript
// this is a Typescript implemented example
import * as basktt from '@basktt/langlib';
const basktt = new Code(null);
function Main() {
     // main function
     Code.ball(Set.var(name === `
     "Miguel",
     "Johnny",
     `));
     Code.ball(text("Hello, ${name}!"));
     Code.ball(return(null));
     Code.ball(if(name === "Miguel") {
        ball.text("Hello, " + $name + "!");
     });
     Code.ball(if(name === "Johnny") {
        ball.do(null);
     });
}
```
- [ ] Add class support: 
```typescript
// ...same code as above...
Code.ball(New.Class({
    ball.text("This is a class in Basktt!");
    ball.End(New.Class);
}))
```

- [ ] Add a Basktt to JavaScript compiler
- [ ] Make code error definition like:
```bash
Ball.loap(!func); # <--- code that caused the error
^^^^^^^^^^^^^^^^
Unexpected token at 32:12. # <--- where is the error
BS012BE1 # <--- error code
```
